# -*- coding: utf-8 -*-
"""Business_Sales_Analysis_SQLite_Python .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YYT0jHR4Me7ocmhngBZoCpDNYRZtz5cJ

# Business Sales Analysis
**SQL + Python Analytics Portfolio Project**

This notebook analyzes e-commerce sales data using SQL queries and Python visualizations.

**Skills demonstrated:**
- SQL — JOINs, GROUP BY, CASE WHEN, aggregations, window functions
- Python — pandas, plotly, data wrangling
- Data Viz — interactive charts, KPI dashboards
- Business Thinking — margins, trends, customer segmentation, discount analysis

## 1. Setup & Data Generation
I created a realistic synthetic dataset with 5,000 orders, 500 customers, and 15 products.
The data includes seasonality, discount tiers, regions, and sales channels.
"""

import sqlite3
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

random.seed(42)
np.random.seed(42)

print("Libraries loaded")

# synthetic data

NUM_CUSTOMERS = 500
NUM_ORDERS = 5000
START_DATE = datetime(2024, 1, 1)
END_DATE = datetime(2025, 12, 31)

PRODUCTS = {
    "Wireless Earbuds":   {"category": "Electronics", "base_price": 59.99,  "cost": 22.00},
    "Phone Case":         {"category": "Electronics", "base_price": 19.99,  "cost": 4.50},
    "USB-C Cable":        {"category": "Electronics", "base_price": 12.99,  "cost": 2.80},
    "Bluetooth Speaker":  {"category": "Electronics", "base_price": 89.99,  "cost": 35.00},
    "Laptop Stand":       {"category": "Electronics", "base_price": 44.99,  "cost": 15.00},
    "Running Shoes":      {"category": "Apparel",     "base_price": 119.99, "cost": 45.00},
    "Hoodie":             {"category": "Apparel",     "base_price": 49.99,  "cost": 18.00},
    "Baseball Cap":       {"category": "Apparel",     "base_price": 24.99,  "cost": 7.00},
    "Yoga Mat":           {"category": "Fitness",     "base_price": 34.99,  "cost": 10.00},
    "Water Bottle":       {"category": "Fitness",     "base_price": 22.99,  "cost": 5.50},
    "Resistance Bands":   {"category": "Fitness",     "base_price": 14.99,  "cost": 3.00},
    "Desk Lamp":          {"category": "Home",        "base_price": 39.99,  "cost": 14.00},
    "Scented Candle":     {"category": "Home",        "base_price": 16.99,  "cost": 4.00},
    "Throw Blanket":      {"category": "Home",        "base_price": 29.99,  "cost": 9.00},
    "Coffee Mug":         {"category": "Home",        "base_price": 14.99,  "cost": 3.50},
}

REGIONS = ["Northeast", "Southeast", "Midwest", "Southwest", "West"]
CHANNELS = ["Website", "Mobile App", "Social Media", "Email Campaign"]
STATUSES = ["Completed", "Completed", "Completed", "Completed", "Returned", "Cancelled"]

FIRST_NAMES = ["Emma", "Liam", "Olivia", "Noah", "Ava", "Ethan", "Sophia", "Mason",
               "Isabella", "James", "Mia", "Logan", "Charlotte", "Lucas", "Amelia"]
LAST_NAMES = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
              "Davis", "Rodriguez", "Martinez", "Wilson", "Anderson", "Thomas", "Lee"]

# --- Generate customers ---
customers = []
for i in range(1, NUM_CUSTOMERS + 1):
    customers.append({
        "customer_id": i,
        "name": f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}",
        "email": f"customer{i}@email.com",
        "region": random.choice(REGIONS),
        "signup_date": (START_DATE + timedelta(days=random.randint(0, 365))).strftime("%Y-%m-%d"),
    })

# Generate orders
orders = []
product_names = list(PRODUCTS.keys())

for i in range(1, NUM_ORDERS + 1):
    customer = random.choice(customers)
    day_offset = random.randint(0, (END_DATE - START_DATE).days)
    order_date = START_DATE + timedelta(days=day_offset)

    # Seasonal boost for holidays
    if order_date.month in [11, 12] and random.random() < 0.3:
        target_month = random.choice([11, 12])
        # Determine the maximum valid day for the target month
        max_day = 30 if target_month == 11 else 31 # November has 30 days, December has 31

        # Ensure the day is not out of range for the new month
        new_day = min(order_date.day, max_day)

        order_date = order_date.replace(month=target_month, day=new_day)

    product_name = random.choice(product_names)
    product = PRODUCTS[product_name]
    quantity = random.choices([1, 2, 3, 4, 5], weights=[50, 25, 15, 7, 3])[0]
    discount = random.choices([0, 0.1, 0.15, 0.2, 0.25], weights=[60, 15, 10, 10, 5])[0]
    unit_price = round(product["base_price"] * (1 - discount), 2)
    total = round(unit_price * quantity, 2)
    cost = round(product["cost"] * quantity, 2)

    orders.append({
        "order_id": i,
        "customer_id": customer["customer_id"],
        "order_date": order_date.strftime("%Y-%m-%d"),
        "product": product_name,
        "category": product["category"],
        "quantity": quantity,
        "unit_price": unit_price,
        "total_revenue": total,
        "total_cost": cost,
        "profit": round(total - cost, 2),
        "discount_pct": int(discount * 100),
        "channel": random.choice(CHANNELS),
        "status": random.choice(STATUSES),
        "region": customer["region"],
    })

df_customers = pd.DataFrame(customers)
df_orders = pd.DataFrame(orders)

# Load into SQLite
conn = sqlite3.connect(":memory:")  # In-memory database (no files needed)
df_customers.to_sql("customers", conn, if_exists="replace", index=False)
df_orders.to_sql("orders", conn, if_exists="replace", index=False)

# Helper to run queries
def sql(query):
    return pd.read_sql_query(query, conn)

print(f"Database ready")
print(f"  - customers table: {len(df_customers)} rows")
print(f"  - orders table:    {len(df_orders)} rows")
print(f"  - Date range: {START_DATE.date()} → {END_DATE.date()}")
print(f"  - Products: {len(PRODUCTS)} across {len(set(p['category'] for p in PRODUCTS.values()))} categories")

"""## 2. Explore the Data
Quick look at what we're working with.
"""

# Preview the orders table
sql("SELECT * FROM orders LIMIT 5")

# Preview the customers table
sql("SELECT * FROM customers LIMIT 5")

# Quick data quality check
sql("""
    SELECT
        COUNT(*)                              AS total_rows,
        COUNT(DISTINCT order_id)              AS unique_orders,
        COUNT(DISTINCT customer_id)           AS unique_customers,
        COUNT(DISTINCT product)               AS unique_products,
        MIN(order_date)                       AS earliest_order,
        MAX(order_date)                       AS latest_order
    FROM orders
""")

"""## 3. KPI Summary
Top-line business metrics — the numbers a stakeholder sees first.
"""

kpis = sql("""
    SELECT
        COUNT(DISTINCT order_id)                              AS total_orders,
        COUNT(DISTINCT customer_id)                           AS unique_customers,
        ROUND(SUM(total_revenue), 2)                          AS total_revenue,
        ROUND(SUM(profit), 2)                                 AS total_profit,
        ROUND(AVG(total_revenue), 2)                          AS avg_order_value,
        ROUND(SUM(profit) * 100.0 / SUM(total_revenue), 1)   AS profit_margin_pct
    FROM orders
    WHERE status = 'Completed'
""")

k = kpis.iloc[0]
print("=" * 50)
print("  KEY PERFORMANCE INDICATORS")
print("=" * 50)
print(f"  Total Revenue:    ${k['total_revenue']:>12,.2f}")
print(f"  Total Profit:     ${k['total_profit']:>12,.2f}")
print(f"  Orders:           {k['total_orders']:>12,.0f}")
print(f"  Unique Customers: {k['unique_customers']:>12,.0f}")
print(f"  Avg Order Value:  ${k['avg_order_value']:>12,.2f}")
print(f"  Profit Margin:    {k['profit_margin_pct']:>12}%")
print("=" * 50)

"""## 4. Revenue & Profit Trends
How are sales performing over time? Any seasonality?
"""

monthly = sql("""
    SELECT
        strftime('%Y-%m', order_date)  AS month,
        ROUND(SUM(total_revenue), 2)   AS revenue,
        ROUND(SUM(profit), 2)          AS profit,
        COUNT(order_id)                AS order_count
    FROM orders
    WHERE status = 'Completed'
    GROUP BY month
    ORDER BY month
""")

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=monthly["month"], y=monthly["revenue"],
    name="Revenue", line=dict(color="#3b82f6", width=2.5),
    fill="tozeroy", fillcolor="rgba(59,130,246,0.1)"
))
fig.add_trace(go.Scatter(
    x=monthly["month"], y=monthly["profit"],
    name="Profit", line=dict(color="#10b981", width=2.5),
    fill="tozeroy", fillcolor="rgba(16,185,129,0.1)"
))
fig.update_layout(
    title="Monthly Revenue & Profit",
    xaxis_title="", yaxis_title="Amount ($)",
    height=400, template="plotly_dark",
    legend=dict(orientation="h", y=1.1)
)
fig.show()

"""## 5. Product & Category Analysis
Which products and categories are driving the business?
"""

# Revenue by category
categories = sql("""
    SELECT
        category,
        COUNT(order_id)                                        AS orders,
        ROUND(SUM(total_revenue), 2)                           AS revenue,
        ROUND(SUM(profit), 2)                                  AS profit,
        ROUND(SUM(profit) * 100.0 / SUM(total_revenue), 1)    AS margin_pct
    FROM orders
    WHERE status = 'Completed'
    GROUP BY category
    ORDER BY revenue DESC
""")

colors = ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"]

fig = px.bar(
    categories, x="category", y=["revenue", "profit"],
    barmode="group", color_discrete_sequence=["#3b82f6", "#10b981"],
    title="Revenue & Profit by Category",
    labels={"value": "Amount ($)", "category": "", "variable": ""}
)
fig.update_layout(height=400, template="plotly_dark", legend=dict(orientation="h", y=1.1))
fig.show()

# Top 10 products by revenue
top_products = sql("""
    SELECT
        product,
        category,
        SUM(quantity)                  AS units_sold,
        ROUND(SUM(total_revenue), 2)   AS revenue,
        ROUND(SUM(profit), 2)          AS profit,
        ROUND(AVG(discount_pct), 1)    AS avg_discount
    FROM orders
    WHERE status = 'Completed'
    GROUP BY product
    ORDER BY revenue DESC
    LIMIT 10
""")

fig = px.bar(
    top_products, x="revenue", y="product", orientation="h",
    color="category", color_discrete_sequence=colors,
    title="Top 10 Products by Revenue",
    labels={"revenue": "Revenue ($)", "product": ""}
)
fig.update_layout(height=450, template="plotly_dark", yaxis=dict(autorange="reversed"))
fig.show()

"""## 6. Customer Analysis
Who are our best customers? How do regions compare?
"""

# Top 10 customers by total spend (uses a JOIN)
top_customers = sql("""
    SELECT
        c.name                            AS customer,
        c.region,
        COUNT(o.order_id)                 AS orders,
        ROUND(SUM(o.total_revenue), 2)    AS total_spent,
        ROUND(AVG(o.total_revenue), 2)    AS avg_order
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    WHERE o.status = 'Completed'
    GROUP BY o.customer_id
    ORDER BY total_spent DESC
    LIMIT 10
""")

print("Top 10 Customers by Lifetime Value")
print("=" * 65)
top_customers

# Regional performance
regions = sql("""
    SELECT
        region,
        COUNT(order_id)                AS orders,
        COUNT(DISTINCT customer_id)    AS customers,
        ROUND(SUM(total_revenue), 2)   AS revenue,
        ROUND(SUM(profit), 2)          AS profit,
        ROUND(AVG(total_revenue), 2)   AS avg_order_value
    FROM orders
    WHERE status = 'Completed'
    GROUP BY region
    ORDER BY revenue DESC
""")

fig = px.bar(
    regions, x="region", y="revenue",
    color="region", color_discrete_sequence=colors,
    title="Revenue by Region",
    text="revenue",
    labels={"revenue": "Revenue ($)", "region": ""}
)
fig.update_traces(texttemplate="$%{text:,.0f}", textposition="outside")
fig.update_layout(height=400, template="plotly_dark", showlegend=False)
fig.show()

"""## 7. Channel Performance
Which sales channels bring in the most revenue?
"""

channels = sql("""
    SELECT
        channel,
        COUNT(order_id)                AS orders,
        ROUND(SUM(total_revenue), 2)   AS revenue,
        ROUND(SUM(profit), 2)          AS profit,
        ROUND(AVG(total_revenue), 2)   AS avg_order_value
    FROM orders
    WHERE status = 'Completed'
    GROUP BY channel
    ORDER BY revenue DESC
""")

fig = px.pie(
    channels, values="revenue", names="channel",
    title="Revenue by Sales Channel",
    color_discrete_sequence=colors, hole=0.4
)
fig.update_traces(textinfo="label+percent", textfont_size=12)
fig.update_layout(height=400, template="plotly_dark")
fig.show()

"""## 8. Discount Impact Analysis
Are discounts driving volume? What's the tradeoff on margins?
"""

discounts = sql("""
    SELECT
        CASE
            WHEN discount_pct = 0   THEN '0% (None)'
            WHEN discount_pct <= 15 THEN '1-15%'
            WHEN discount_pct <= 20 THEN '16-20%'
            ELSE '21%+'
        END AS discount_tier,
        COUNT(order_id)                                      AS orders,
        ROUND(SUM(total_revenue), 2)                         AS revenue,
        ROUND(SUM(profit) * 100.0 / SUM(total_revenue), 1)  AS margin_pct,
        ROUND(AVG(total_revenue), 2)                         AS avg_order_value
    FROM orders
    WHERE status = 'Completed'
    GROUP BY discount_tier
    ORDER BY discount_tier
""")

fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=("Order Volume by Discount Tier", "Profit Margin by Discount Tier")
)

fig.add_trace(go.Bar(
    x=discounts["discount_tier"], y=discounts["orders"],
    marker_color="#f59e0b", text=discounts["orders"], textposition="outside",
    name="Orders"
), row=1, col=1)

fig.add_trace(go.Bar(
    x=discounts["discount_tier"], y=discounts["margin_pct"],
    marker_color="#10b981", text=discounts["margin_pct"].apply(lambda x: f"{x}%"),
    textposition="outside", name="Margin %"
), row=1, col=2)

fig.update_layout(height=400, template="plotly_dark", showlegend=False,
                  title_text="Discount Impact: Volume vs Margins")
fig.show()

print("\nDiscount summary table:")
discounts

"""## 9. Order Status Breakdown
What percentage of orders are completed vs returned vs cancelled?
"""

status = sql("""
    SELECT
        status,
        COUNT(order_id)                AS orders,
        ROUND(SUM(total_revenue), 2)   AS revenue,
        ROUND(COUNT(order_id) * 100.0 / (SELECT COUNT(*) FROM orders), 1) AS pct_of_total
    FROM orders
    GROUP BY status
    ORDER BY orders DESC
""")

status_colors = {"Completed": "#10b981", "Returned": "#f59e0b", "Cancelled": "#ef4444"}

fig = px.bar(
    status, x="status", y="orders",
    color="status", color_discrete_map=status_colors,
    title="Orders by Status", text="orders",
    labels={"orders": "Number of Orders", "status": ""}
)
fig.update_traces(textposition="outside")
fig.update_layout(height=380, template="plotly_dark", showlegend=False)
fig.show()

status

"""## 10. Key Findings

Summarizing the analysis:
"""

# Pull a few insights programmatically
k = kpis.iloc[0]
top_cat = categories.iloc[0]
top_prod = top_products.iloc[0]
top_region = regions.iloc[0]
top_channel = channels.iloc[0]

return_rate = status[status["status"] == "Returned"]["pct_of_total"].values[0]
cancel_rate = status[status["status"] == "Cancelled"]["pct_of_total"].values[0]

print("=" * 55)
print("  KEY FINDINGS")
print("=" * 55)
print(f"")
print(f"  1. REVENUE: ${k['total_revenue']:,.0f} total across")
print(f"     {int(k['total_orders']):,} completed orders")
print(f"")
print(f"  2. TOP CATEGORY: {top_cat['category']}")
print(f"     ${top_cat['revenue']:,.0f} revenue, {top_cat['margin_pct']}% margin")
print(f"")
print(f"  3. BEST SELLER: {top_prod['product']}")
print(f"     {int(top_prod['units_sold'])} units sold, ${top_prod['revenue']:,.0f} revenue")
print(f"")
print(f"  4. STRONGEST REGION: {top_region['region']}")
print(f"     ${top_region['revenue']:,.0f} revenue from {int(top_region['customers'])} customers")
print(f"")
print(f"  5. TOP CHANNEL: {top_channel['channel']}")
print(f"     ${top_channel['revenue']:,.0f} revenue")
print(f"")
print(f"  6. RETURN RATE: {return_rate}% | CANCEL RATE: {cancel_rate}%")
print(f"")
print(f"  7. DISCOUNTS: Higher discounts boost volume but")
print(f"     compress margins — worth monitoring closely")
print(f"")
print("=" * 55)

# Close the database connection
conn.close()
print("Database connection closed. Analysis complete!")